apiVersion: batch/v1
kind: Job
metadata:
  name: sarscovwp-job
spec:
  template:
    spec:
      containers:
      - name: sarscovwp-job
        image: yash5090/sarscovwp:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
